"""Context management: in-session compression and cross-session handoff.

Two mechanisms:
1. Tool result clearing: Replace stale tool outputs with placeholders (intra-session)
2. Session handoff: Structured handoff documents + bootstrap sequence (inter-session)
"""
import json
import os
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

from .config import Config


@dataclass
class HandoffInfo:
    """Structured information passed from one session to the next."""
    session_id: int
    feature_id: str
    feature_desc: str
    summary: str = ""           # 3-5 sentence session summary
    git_commit: str = ""
    commit_note: str = ""
    unresolved_issues: List[str] = None  # list of "file:line — symptom — suspicion"
    next_action: str = ""  # single concrete next step
    do_not_do: List[str] = None  # things to avoid
    files_to_read: List[str] = None  # paths to re-read (not contents!)

    def __post_init__(self):
        if self.unresolved_issues is None:
            self.unresolved_issues = []
        if self.do_not_do is None:
            self.do_not_do = []
        if self.files_to_read is None:
            self.files_to_read = []

    def to_markdown(self) -> str:
        """Format as structured handoff markdown document."""
        lines = [
            f"# Session {self.session_id} Handoff",
            "",
        ]
        # Session summary (generated by LLM from transcript)
        if self.summary:
            lines.extend([
                "## Session Summary",
                "",
                self.summary,
                "",
            ])
        lines.extend([
            f"## Current Focus",
            f"Feature: {self.feature_id} — {self.feature_desc}",
            "",
            f"## Last Confirmed Working State",
            f"git commit: {self.git_commit or '(not recorded)'}",
            f"Description: {self.commit_note or '(not recorded)'}",
            "",
            "## Unresolved Issues (file:line)",
        ])
        if self.unresolved_issues:
            for issue in self.unresolved_issues:
                lines.append(f"- {issue}")
        else:
            lines.append("- (none)")

        lines.extend([
            "",
            "## Next Action (one concrete step)",
            self.next_action or "(not specified)",
            "",
            "## Do Not Do",
        ])
        if self.do_not_do:
            for item in self.do_not_do:
                lines.append(f"- {item}")
        else:
            lines.append("- (none)")

        lines.extend([
            "",
            "## Files to Re-read (paths only, not contents)",
        ])
        if self.files_to_read:
            for f in self.files_to_read:
                lines.append(f"- {f}")
        else:
            lines.append("- (none)")

        return "\n".join(lines)


def should_end_session(
    messages: List[Dict[str, Any]],
    turn_count: int,
    tokens_used: int,
    config: Config,
    feature_completed: bool = False,
    used_tokens_from_api: int = 0,  # precise token count from API usage fields
) -> Tuple[bool, str]:
    """Determine if the current session should end.

    Uses precise token counts from API usage (not char/4 estimation) per the
    implementation plan's emphasis on accurate context window tracking.

    Returns (should_end, reason).
    """
    # Use API-reported tokens when available, fall back to rough estimate
    effective_tokens = used_tokens_from_api if used_tokens_from_api > 0 else tokens_used
    token_threshold = config.session.switch_ratio * config.session.context_window

    # Check 1: Token threshold exceeded
    if effective_tokens >= token_threshold:
        return (True, f"token_threshold ({effective_tokens}/{config.session.context_window})")

    # Check 2: Turn limit exceeded
    if turn_count >= config.session.max_turns:
        return (True, f"turn_limit ({turn_count}/{config.session.max_turns})")

    # Check 3: Natural milestone boundary — prefer to switch here
    if feature_completed:
        return (True, "milestone_boundary")

    return (False, "")


def clear_stale_tool_results(
    messages: List[Dict[str, Any]],
    current_turn: int,
    config: Config,
) -> List[Dict[str, Any]]:
    """Replace stale tool results with placeholder text.

    This is the safest, lightest compression method: tool results from old turns
    are replaced with a brief summary placeholder, preserving the fact that the
    tool was called but not the full output. The model can re-read files if needed.

    Only clears results older than K rounds and exceeding a minimum token threshold.
    """
    K = config.context.tool_result_clearing_rounds
    min_tokens = config.context.tool_result_min_tokens

    cleaned = []
    # Track turn numbers to know which tool results are stale
    turn_idx = 0
    for i, msg in enumerate(messages):
        if msg.get("role") == "assistant" and msg.get("tool_calls"):
            turn_idx += 1

        if msg.get("role") == "tool":
            tool_turn = turn_idx  # the turn this tool result belongs to
            rounds_ago = current_turn - tool_turn

            if rounds_ago > K:
                content = msg.get("content", "")
                est_tokens = len(content) // 4
                if est_tokens > min_tokens:
                    # Replace with placeholder
                    cleaned_msg = dict(msg)
                    cleaned_msg["content"] = (
                        f"[Cleared: tool result from turn {tool_turn}, "
                        f"{rounds_ago} turns ago. Original output ~{est_tokens} tokens."
                        f"Re-read relevant files if you need this information.]"
                    )
                    cleaned.append(cleaned_msg)
                    continue

        cleaned.append(msg)

    return cleaned


def compress_messages(
    messages: List[Dict[str, Any]],
    current_turn: int,
    config: Config,
    used_tokens: int,
) -> List[Dict[str, Any]]:
    """Apply compression strategies to keep context within budget.

    Currently implements tool result clearing. Returns the compressed message list.
    """
    token_threshold = int(config.session.switch_ratio * config.session.context_window)

    if used_tokens < token_threshold * 0.5:
        # Still plenty of room, no compression needed
        return messages

    # Apply tool result clearing
    return clear_stale_tool_results(messages, current_turn, config)


def get_latest_handoff_path(handoffs_dir: str) -> Optional[str]:
    """Find the most recent handoff document."""
    if not os.path.isdir(handoffs_dir):
        return None
    files = sorted([f for f in os.listdir(handoffs_dir) if f.endswith(".md")], reverse=True)
    if not files:
        return None
    return os.path.join(handoffs_dir, files[0])


def parse_handoff_doc(content: str) -> HandoffInfo:
    """Parse a handoff markdown document back into structured info."""
    info = HandoffInfo(session_id=0, feature_id="", feature_desc="")

    # Extract session ID
    m = re.search(r'Session (\d+)', content)
    if m:
        info.session_id = int(m.group(1))

    # Extract feature info
    m = re.search(r'Feature: ([^\s]+)\s*[—–-]\s*(.+?)$', content, re.MULTILINE)
    if m:
        info.feature_id = m.group(1).strip()
        info.feature_desc = m.group(2).strip()

    # Extract git commit
    m = re.search(r'git commit: (.+?)$', content, re.MULTILINE)
    if m:
        info.git_commit = m.group(1).strip()

    # Extract next action
    action_section = re.search(r'## Next Action \(one concrete step\)\n(.+?)(?=\n## |\Z)', content, re.DOTALL)
    if action_section:
        info.next_action = action_section.group(1).strip()

    # Extract unresolved issues
    issues_section = re.search(r'## Unresolved Issues.*?\n(.*?)(?=\n## |\Z)', content, re.DOTALL)
    if issues_section:
        for line in issues_section.group(1).strip().split("\n"):
            line = line.strip()
            if line.startswith("- "):
                issue = line[2:]
                if issue != "(none)":
                    info.unresolved_issues.append(issue)

    # Extract do-not-do items
    dnd_section = re.search(r'## Do Not Do\n(.*?)(?=\n## |\Z)', content, re.DOTALL)
    if dnd_section:
        for line in dnd_section.group(1).strip().split("\n"):
            line = line.strip()
            if line.startswith("- "):
                item = line[2:]
                if item != "(none)":
                    info.do_not_do.append(item)

    # Extract files to read
    files_section = re.search(r'## Files to Re-read.*?\n(.*?)(?=\n## |\Z)', content, re.DOTALL)
    if files_section:
        for line in files_section.group(1).strip().split("\n"):
            line = line.strip()
            if line.startswith("- "):
                f = line[2:]
                if f != "(none)":
                    info.files_to_read.append(f)

    return info


def _rel_path(config: Config, abs_path: str) -> str:
    """Convert an absolute path to a project-root-relative path for bootstrap instructions."""
    try:
        rel = os.path.relpath(abs_path, config.project_root)
        if not rel.startswith("."):
            rel = "./" + rel
        return rel
    except ValueError:
        return abs_path


def build_bootstrap_messages(
    config: Config,
    task_state_path: str,
    spec_path: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """Build the fixed bootstrap sequence for a new coding agent session.

    This is the canonical "getting up to speed" sequence that every new session
    must execute before starting work on the selected feature.

    NOTE: All paths are converted to project-root-relative paths so the LLM never
    learns absolute host paths. When runtime_container is enabled, the tool layer
    (tools.py) resolves relative paths -> host paths -> container (/workspace/...)
    transparently — see _resolve_path() and _to_container_path().
    """
    handoff_path = get_latest_handoff_path(config.paths.handoffs_dir)

    # Convert absolute paths to project-root-relative so the LLM never sees host paths
    rel_memory = _rel_path(config, config.paths.memory_dir)
    rel_state = _rel_path(config, task_state_path)
    rel_handoff = _rel_path(config, handoff_path) if handoff_path else None
    rel_skills = _rel_path(config, config.paths.skills_dir)

    # Build conditional sections
    handoff_step = ""
    if handoff_path and os.path.exists(handoff_path) and rel_handoff:
        handoff_step = (
            f"### Step 4: Read Handoff Document\n"
            f"Run: `read: {rel_handoff}`\n"
            f"This is the specific handoff information from the previous session.\n\n"
        )

    spec_step = ""
    step_offset = 0
    if spec_path:
        rel_spec = _rel_path(config, spec_path)
        step_num = 4 + (1 if handoff_step else 0)
        spec_step = (
            f"### Step {step_num}: Read Original Task Specification\n"
            f"Run: `read: {rel_spec}`\n"
            f"Read the original task specification. This contains precise API signatures, "
            f"pseudo-code, and detailed requirements that the Planner's summary may have condensed. "
            f"Always prefer the spec's exact signatures over your own conventions.\n\n"
        )
        step_offset = 1

    # Compute dynamic step numbers
    base = 4 + (1 if handoff_step else 0) + step_offset
    step_skills = base + 1
    step_decisions = base + 2
    step_facts = base + 3
    step_env = base + 4
    step_start = base + 5

    # Load bootstrap template from prompts directory
    template = load_system_prompt(
        os.path.join(os.path.dirname(__file__), "prompts"),
        "bootstrap",
    )
    bootstrap_text = template.format(
        rel_memory=rel_memory,
        rel_state=rel_state,
        rel_skills=rel_skills,
        handoff_step=handoff_step,
        spec_step=spec_step,
        step_skills=step_skills,
        step_decisions=step_decisions,
        step_facts=step_facts,
        step_env=step_env,
        step_start=step_start,
    )

    return [{"role": "user", "content": bootstrap_text}]


def load_system_prompt(prompts_dir: str, role: str = "coding_agent") -> str:
    """Load a system prompt from the prompts directory."""
    path = os.path.join(prompts_dir, f"{role}.md")
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    return "You are a helpful coding agent."
